# Generated by Django 3.0.7 on 2020-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=15, verbose_name='标题')),
                ('centen', models.CharField(max_length=1500, verbose_name='内容')),
                ('createTime', models.CharField(max_length=15, verbose_name='创建时间')),
                ('group', models.CharField(max_length=15, verbose_name='手机')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
